// Package xogen contains the types for schema 'public'.
package xogen

// GENERATED BY XO. DO NOT EDIT.

// Group represents a row from 'public.group'.
type Group struct {
	ID   int    `json:"id"`   // id
	Name string `json:"name"` // name
}
