// Package xogen contains the types for schema 'public'.
package xogen

// GENERATED BY XO. DO NOT EDIT.

import (
	"database/sql"
)

// UserViewer represents a row from 'public.user_viewer'.
type UserViewer struct {
	ID   sql.NullInt64  `json:"id"`   // id
	Name sql.NullString `json:"name"` // name
}
