// Code generated by "stringer -type=SenarioType ./wepay/consts-ts.go"; DO NOT EDIT.

package wepay

import "fmt"

const _SenarioType_name = "TSenarioKnownTSenarioWechatTSenarioH5TSenarioNative2"

var _SenarioType_index = [...]uint8{0, 13, 27, 37, 52}

func (i SenarioType) String() string {
	if i < 0 || i >= SenarioType(len(_SenarioType_index)-1) {
		return fmt.Sprintf("SenarioType(%d)", i)
	}
	return _SenarioType_name[_SenarioType_index[i]:_SenarioType_index[i+1]]
}
